cursor            #80d4d9
cursor_text_color #003739

foreground            #dde4e4
background            #090f10
selection_foreground  #1b3436
selection_background  #b1cccd
url_color             #b1cccd

#: black 000000 767676
color0  #0e1415
color8  #303636
#: red cc0403 f2201f
#color1  #38b4bb
#color9  #a7e1e5
#: green 19cb00 23fd00
#color2  #b1cccd
#color10 #cce8e9
#: yellow cecb00 fffd00
#color3  #b6c7e9
#color11 #d6e3ff
#: blue 0d73cc 1a8fff
#color4  #004f53
#color12 #80d4d9
##: magenta cb1ed1 fd28ff
#color5  #324b4d
#color13 #b1cccd
#: cyan 0dcdcd 14ffff
#color6  #364764
#color14 #b6c7e9
#: white dddddd ffffff
color7  #bec8c9
color15 #dde4e4

#color0 #000000
#color8 #545454
color1 #ff5555
color9 #ff5454
color2 #50fa7b
color10 #50fa7b
color3 #f0fa8b
color11 #f0fa8b
color4 #bd92f8
color12 #bd92f8
color5 #ff78c5
color13 #ff78c5
color6 #8ae9fc
color14 #8ae9fc
#color7 #bbbbbb
#color15 #ffffff

mark1_foreground #002022
mark1_background #9cf0f6
mark2_foreground #041f21
mark2_background #cce8e9
mark3_foreground #081c36
mark3_background #d6e3ff

active_tab_foreground #003739
active_tab_background #80d4d9
inactive_tab_foreground #9cf0f6
inactive_tab_background #004f53

active_border_color #80d4d9
inactive_border_color #003739
# bell_border_color #ff5a00
